var queue = require('./structs/queue');
var BINNED_QUEUES = queue.binRanges();
var ENQUEUED_PLAYERS = new Set();
var DEQUEUED_PLAYERS = {}
var MMR_LOOKUP = queue.genKeyLookup();
var PROPERTIES = new Object();

PROPERTIES.MMR_LOOKUP = MMR_LOOKUP;
PROPERTIES.BINNED_QUEUES = BINNED_QUEUES;
PROPERTIES.ENQUEUED_PLAYERS = ENQUEUED_PLAYERS;
PROPERTIES.DEQUEUED_PLAYERS = DEQUEUED_PLAYERS;

module.exports = PROPERTIES;
